const { withAppBuildGradle } = require('@expo/config-plugins');

/**
 * Expo Config Plugin to rename the output APK file generated by Android Gradle.
 * Resulting APK format: PersonalMoneyManager-v<version>-<variant>.apk
 * Example: PersonalMoneyManager-v1.0.0-preview.apk / PersonalMoneyManager-v1.0.0-release.apk
 */
const withCustomApkName = (config) => {
  return withAppBuildGradle(config, (config) => {
    const buildGradle = config.modResults.contents;

    const customBlock = `
// [Custom APK Naming Plugin]
android {
    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "PersonalMoneyManager-v\${variant.versionName ?: '1.0.0'}-\${variant.name}.apk"
        }
    }
}
`;

    if (!buildGradle.includes('PersonalMoneyManager-v')) {
      config.modResults.contents = buildGradle + '\n' + customBlock;
    }

    return config;
  });
};

module.exports = withCustomApkName;